### ISSUE TITLE
Ability to load binary file dependencies

### ISSUE THREAD

**Issue by gonzojive** [requirejs/text#104]
Example test case:
```
define(
  ['chai', 'binary!file.xlsx'],
  function(chai, f) {
    describe('xlsx.read works', function(){
      it('Should be 10 bytes long.', function() {
        chai.assert.strictEqual(10, f.length);
      });
    });
  });
```

**Comment by jrburke** [comment]
I think it best to create a different loader plugin for binary needs, it would likely be able to set up a better contract than piggy backing on the text plugin. I do not have any concrete code to suggest for that type of plugin, and probably would have a hard time working with the optimizer for use in file concatenation.

It might be best in those cases to just use regular XMLHttpRequest calls or other mechanisms to get the data instead of using the module system.
