### ISSUE TITLE
domain is https, can not loaded html 

### ISSUE THREAD

**Issue by 3vand0ng** [requirejs/text#115]
hi,This is Chrome console log message,How to fixed this problem?
pls help me...
Mixed Content: The page at 'https://xxxxxxxx/account/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxxxxx/public/app/views/xxxx.html'. This request has been blocked; the content must be served over HTTPS.

**Comment by jrburke** [comment]
This seems to be a paths configuration issue, not something with the text plugin in particular. Without knowing more, my guess is that there is a paths config that points to an http: URL instead of using https. If you wanted the config to be flexible, start with a path just has the '//domain.com/' part, leave off the http: or https: part and that should fix it.
