### ISSUE TITLE
relative url fails when configuring baseUrl

### ISSUE THREAD

**Issue by mildred** [requirejs/text#96]
Let's say I have a configuration with

    baseUrl: "Aloha-Editor/src",
    paths: { text: "../../text" }

And I have a module which name is `../../edit/main` (that is located in `edit/main.js` relative to project root). That module requires `text!./style.css` located in `edit/style.css`.

When I use r.js to bundle everything together, I have the following error:

    Tracing dependencies for: ../../edit/main
    Error: Error: Loader plugin did not call the load callback in the build:
    text:
      text!style.css: Error: ENOENT, no such file or directory '/project/dir/Aloha-Editor/src/style.css'
    Module loading did not complete for: ../../edit/main
        at Function.build.checkForErrors (/project/dir/r.js:27416:19)

**Comment by jiagang** [comment]
I have a similar issue, this is my directory

```
js
|-app
| |-module1.js
|-module2.js
|-test.html
index.html
```

These is index.html with configuration `baseUrl: './js/app'` and required module1, module1 requires module2 with `define(['../module2'], function(){})`, module2 requires test.html with `define(['text:./test.html', function(){}])`,
Now I can't get correct path of test.html, browser requested `./js/app/../../../test.html` but it should be `./js/app/../test.html`.

**Comment by purtuga** [comment]
I'm also having the same issue..I know this is an old thread, but was there any resolution to the issue?

**Comment by jrburke** [comment]
module IDs that if resolved leave the baseUrl directory are hard to resolve correctly. It is best to use paths config to make sure the module IDs do not end up with '../' as part of the resolved ID:

So if `baseUrl: './app'`, and `require(['main'])`, that would load from ./app/main.js, and if in that file, there is a dependency on `'../resource/one'`, the loader has a hard time resolving that to an absolute module ID: 'main' + '../resource/one' is outside the root of the module ID space. So it is best to put in a `paths: { resource: '../resource'`, and then `main` can depend on 'resource/one` and it will work out.

Long term, like in a 3.0 release, I just want the loader to throw on that case, instead of just try to a path that will likely break in some way, particularly in an optimization, but stuck with it for the 2.x series.

Closing as I believe the ../something outside the root of the module ID space is the core issue, with the paths config as the solution to fixing it.
